### ISSUE TITLE
Missing tokens tracker

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#1221]
This is an issue to track all missing tokens for the token analysis. Comment below with any additional missing tokens. Currently known:

- [x] Tokens and emblems for the back side of all flip cards.
- [ ] Morph and manifest tokens
- [ ] Adorned Pouncer
- [x] Young Pyromancer
- [ ] Nahiri, the Lithomancer
- [ ] Sword of Body and Mind

**Comment by dekkerglen** [comment]
- [ ] Elf Warrior, generated by Imperious Perfect.
- [ ] The First Iroan Games not listed as a generator for 1/1 Human Soldiers.

**Comment by dekkerglen** [comment]
- [ ] Treasure, from Vraska, Relic Seeker

**Comment by cubefortwo** [comment]
Garruk Relentless 2/2 wolf

**Comment by cubefortwo** [comment]
Garruk, Cursed Huntsman 2/2 black/green wolf tokens

**Comment by ruler501** [comment]
[ ] First Iroan Games, 1/1 Human Soldier

**Comment by pino-cc** [comment]
planeswalker Arlinn Kord makes a 2/2 green wolf token

**Comment by DrewHoyt** [comment]
Tireless Tracker - Clue tokens

**Comment by dekkerglen** [comment]
[] all elspeth tokens
[] Ashaya token from Nissa

**Comment by oscarhermoso** [comment]
- [ ] Dreadhorde Invasion - Zombie Army token

**Comment by AGFeldman** [comment]
- [ ] Meloku the Clouded Mirror - Illusion token

**Comment by dekkerglen** [comment]
[ ] Initiative tokens for all initiative cards

**Comment by MuttonBash** [comment]
- [ ] Forth Eorlingas (The monarch)
- [ ] Outland Liberator (Day / Night Tracker)
- [ ] Ocelot Pride (City's Blessing)
